extends:
  - standard-with-typescript
parserOptions:
  project: ./tsconfig.json
rules:
  '@typescript-eslint/restrict-plus-operands':
    - error
    - allowAny: false
      allowBoolean: false
      allowNullish: false
