'*.{ts,tsx,js}':
  - 'eslint --cache --cache-location ./node_modules/.cache/eslint --fix'
  - 'prettier --loglevel warn --cache --write'
'*.scss':
  - 'stylelint --cache --cache-location ./node_modules/.cache/stylelint --fix'
  - 'prettier --loglevel warn --cache --write'
'*.{json,yml}': 'prettier --loglevel warn --cache --write'
